---
# Provision instances in AWS specific to the Linux-Apache HA Proxy demo
- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  
  - set_fact: ec2_region=us-east-2
  - set_fact: iam_role=ec2
  - set_fact: ec2_image=ami-03291866
  - set_fact: ec2_keypair=ec2-ocp.pem
  - set_fact: subnet_to_use=subnet-e419d49e
  - set_fact: ec2_security_group=sg-315cd65b
  - set_fact: ec2_instance_type=t2.micro
  - set_fact: ec2_instance_count=2
  
  - name: Launch webserver instances
    ec2:
#      access_key: "{{ ec2_access_key }}"
#      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      volumes:
         - device_name: /dev/sda1
           volume_size: 10
           delete_on_termination: true
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'webservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
      count: "{{ ec2_instance_count }}"
      wait: true
    register: ec2

  - name: Launch load balancing instance
    ec2:
#      access_key: "{{ ec2_access_key }}"
#      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      volumes:
         - device_name: /dev/sda1
           volume_size: 10
           delete_on_termination: true
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'lbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
      count: "1"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
