
- hosts: tag_ansible_group_webservers
  tasks:
  - name: enable firewalld
    systemd: state=started name=firewalld

  - name: Enable firewall TCP access for httpd port
    firewalld: port={{httpd_port}}/tcp immediate=true permanent=true state=enabled

- hosts: tag_ansible_group_lbservers
  tasks:
  - name: enable firewalld
    systemd: state=started name=firewalld

  - name: Enable firewall TCP access for ha_proxy port
    firewalld: port={{listenport}}/tcp immediate=true permanent=true state=enabled

