---
## This playbook deploys the haproxy and webservers to this site.  

# Apply common configuration to all hosts
- hosts: tag_ansible_group
  gather_facts: yes

  roles:
  - common

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: tag_ansible_group_webservers
  gather_facts: yes
  
  roles:
  - base-apache
  - web
  - php-fpm
  - mysql
  
  tags:
  - web

#configure Mysql


# Configure and deploy the load balancer(s).
- hosts: tag_ansible_group_lbservers
  gather_facts: yes
  
  roles:
  - haproxy
  
  tags:
  - lb
