---
#- name: Install Repo
# yum: 
#     name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
#     state: present
#  when: "'{{ db }}' in inventory_hostname"

- name: enable MySQL5.6 Repo
  yum_repository:
    name: MySQL5.6
    description: MySQL5 YUM repo
    baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/6/$basearch/
    enabled: yes
    repo_gpgcheck: no
  when: "'{{ db }}' in inventory_hostname"

- name: "MySQL: yum: packages: MySQL5.6CommunityServer"
  yum:
     name: "{{item}}"
     state: present
  with_items:
    - mysql-server
    - mysql-libs
    - mysql-connector-java
    - mysql-devel
    - MySQL-python
  when: "'{{ db }}' in inventory_hostname"
  becyome: yes

- name: "MySQL: service: ensure mysql started"
  service:
    name: mysqld
    state: started
    enabled: yes
  when: "'{{ db }}' in inventory_hostname"

- name: "MySQL: mysql_user: update mysql root password for all root accounts"
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{default_password}}"
    priv: ".:ALL,GRANT"
    login_user: root
    login_password: ""
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true
  when: "'{{ db }}' in inventory_hostname"

- name : "MySQL: service: ensure mysql started"
  service:
    name: mysqld
    state: started
    enabled: yes
  when: "'{{ db }}' in inventory_hostname"

- name: "MySQL: template: .my.cnf file to /root"
  template:
    src: ../templates/.my.cnf
    dest: "/root"
    owner: "{{linux_admin_id}}"
    mode: 0600
  when: "'{{ db }}' in inventory_hostname"

- name: "MySQL: mysql_user: Change Root password"
  mysql_user:
    name: root
    password: "{{default_password}}"
    update_password: always
  when: "'{{ db }}' in inventory_hostname"